#!/bin/bash 
#==========================================
#Name:isohub
#Autor:h0lik@linux
#GitHub:github.com/h0lik
#WebSite:https://soraxlab.ru
#Date:23.09.2024
#==========================================
dir=/opt/isohub/
lib=/opt/isohub/lib
source $lib/ubuntu
source $lib/debian
source $lib/alma
source $lib/rockly
source $lib/fedora-server
source $lib/alpine
source $lib/centos
source $lib/createpool
helpfunc() {
echo -e "========================================"
echo -e "Script download ISO"
echo -e "========================================"
echo -e "ISO minimal"
echo -e " -h | --help "
echo -e " -u | --update git repo"
echo -e " -c | --create-pool Specify the storage location ISO"
echo -e " -t | --test Testing Pool Entry test"
echo -e " --rockly8  | Rockly Linux 8.10 netinst"
echo -e " --rockly9  | Rockly Linux 9 netinst"
echo -e " --alma8    | Alma Linux 8.10 netinst"
echo -e " --alma9    | Alma Linux 9 netinst"
echo -e " --debina11 | Debian Linux 11 netinst"
echo -e " --debian12 | Debian Linux 12 netinst"
echo -e " --ubuntu-serv20.03 | Ubuntu Server 20.04 netinst"
echo -e " --ubuntu-serv22.04 | Ubuntu Server 22.04 netinst"
echo -e " --ubunut-serv23.04 | Ubuntu Server 23.04 netinst"
echo -e " --ubuntu-serv24.04 | Ubuntu Server 24.04 netinst"
echo -e " --Fedora-server39  | Fedora Server 39 netinst"
echo -e " --centos9 | CentOS - 9 netinst"
echo -e " --alpine  | Alpine Linux netinst"
echo -e "---------------------------------------"
echo -e "$ isohub --debain12"
echo -e "---------------------------------------"
echo -e "======================================="
}
update() {
	cd $dir
	git pull origin main

}


while [ -n "$1" ]
do
	case "$1" in 
	-h | --help )helpfunc;;
	-u | --update)update ;;
	-c | --create-pool)createpoolFync ;;
	-е | --test)testpoolFync ;;
	--rockly8)rockly8 ;;
	--rockly9)rockly9 ;;
	--alma8)alma8 ;;
	--alma9)alma9 ;;
	--debian11)debian11 ;;
	--debian12)debian12 ;;
	--ubuntu-serv20.04)ubuntu_server_20 ;;
	--ubuntu-serv22.04)ubuntu_server_22 ;;
	--ubuntu-serv23.04)ubuntu_server_23 ;;
	--ubunut-serv24.04)ubuntu_server_24 ;;
	--fedora-server39)fedora39srv ;;
	--centos9)centos9 ;;
	--alpine)alpine;;
esac 
shift 
done 
